;; A real editor buffer for longer messages; source context remains pinned outside it.
(require "helix/editor.scm")
(require "helix/misc.scm")
(require (prefix-in cmd. "helix/commands.scm"))
(require (prefix-in loc. "location.scm"))
(require-builtin helix/core/static as edit.)
(require-builtin helix/core/editor as core.)
(require-builtin helix/core/text as text.)
(provide open-composer composer-doc? composer-active? composer-text close-composer composer-origin)
(define document (box #f))
(define origin (box #f))
(define retained (box ""))
(define notify (box void))
(define (composer-origin) (unbox origin))
(define (composer-doc? id) (equal? id (unbox document)))
(define (composer-active?)
  (and (unbox document) (editor-doc-exists? (unbox document))))
(define (composer-text)
  (if (composer-active?) (text.rope->string (editor->text (unbox document))) (unbox retained)))
(define (open-composer draft stash)
  (set-box! notify stash)
  (if (composer-active?)
      (core.editor-switch-action! (unbox document) (Action/Replace))
      (begin
        (set-box! origin (loc.bookmark))
        (cmd.new)
        (set-box! document (editor->doc-id (editor-focus)))
        (set-scratch-buffer-name! "Tandem message · Space t s send · Space t q keep draft")
        (edit.insert_mode)
        (when (> (string-length draft) 0) (edit.insert_string draft))))
  (set-status! "Message editor: normal Helix keys. Space t s sends; Space t q returns with your draft."))
(define (close-composer)
  (when (composer-active?)
    (set-box! retained (composer-text))
    (core.editor-switch-action! (unbox document) (Action/Replace))
    (edit.normal_mode)
    (cmd.buffer-close!))
  (set-box! document #f)
  (loc.restore (unbox origin)))
;; Keep text if the user closes the buffer with Helix's own :bc! command.
(register-hook 'document-focus-lost
  (lambda (doc) (when (and (composer-doc? doc) (composer-active?)) (set-box! retained (composer-text)) ((unbox notify) (unbox retained)))))

(register-hook 'document-closed
  (lambda (event)
    (when (composer-doc? (doc-closed-id event))
      (set-box! retained (text.rope->string (doc-closed-text event)))
      ((unbox notify) (unbox retained))
      (set-box! document #f))))
