;; Native code views: baseline on the left, editable current source on the right.
(require "helix/editor.scm")
(require "helix/misc.scm")
(require (prefix-in cmd. "helix/commands.scm"))
(require (prefix-in loc. "location.scm"))
(require (prefix-in chat. "chat.scm"))
(require-builtin helix/core/editor as core.)
(require-builtin helix/core/static as edit.)
(require-builtin helix/core/text as text.)
(provide open-comparison close-comparison comparison-active? comparison-doc?)
(define state (box #f))
(define documents (box (list)))
(define (comparison-active?) (if (unbox state) #t #f))
(define (comparison-doc? doc) (if (member doc (unbox documents)) #t #f))
;; Enumerate through native window navigation; never dereference a stale ViewId.
(define (views)
  (if (null? (filter editor-doc-in-view? (editor-all-documents))) (list)
    (let ([first (editor-focus)])
      (let loop ([found (list first)])
        (edit.rotate_view)
        (if (equal? first (editor-focus)) found
          (loop (cons (editor-focus) found)))))))
(define (snapshot name content language)
  (cmd.new)
  (set-box! documents (cons (editor->doc-id (editor-focus)) (unbox documents)))
  (set-scratch-buffer-name! name)
  (when language (cmd.set-language language))
  (unless (equal? content "")
    (edit.insert_mode)
    (edit.insert_string content)
    (edit.normal_mode)))
(define (position line)
  (cmd.goto-line (max 1 (min (inexact->exact line)
                         (text.rope-len-lines (editor->text (editor->doc-id (editor-focus)))))))
  (edit.align_view_top))
(define (open-comparison data)
  (let* ([mark (loc.bookmark)] [left (editor-focus)]
         [language (editor-document->language (hash-ref mark 'doc))]
         [chat-state (chat.chat-state)]
         [file (hash-ref data 'file)]
         [old (hash-ref data 'old)]
         [current (hash-ref data 'current)])
    (chat.chat-close)
    (snapshot (string-append (if (string? old) "Old · " "Old (new file) · ") file)
      (if (string? old) old "")
      language)
    (position (hash-ref data 'old_line))
    (core.editor-switch-action! (hash-ref mark 'doc) (Action/VerticalSplit))
    (if (string? current)
      (cmd.open (hash-ref data 'current_file))
      (snapshot (string-append "Current · " file " · deleted") "" language))
    (position (hash-ref data 'current_line))
    (set-box! state (hash 'origin mark 'left left 'right (editor-focus) 'chat chat-state))
    (set-status! "Old ← | → Current · Ctrl-w h/l switch · Space t p close")))
(define (close-comparison)
  (when (unbox state)
    (let* ([saved (unbox state)] [live (views)]
           [left (hash-ref saved 'left)]
           [right (hash-ref saved 'right)])
      (set-box! state #f)
      (when (and (member left live) (member right live))
        (editor-set-focus! right)
        (cmd.quit!))
      (let ([remaining (views)])
        (unless (null? remaining)
          (cond [(member left remaining) (editor-set-focus! left)]
            [(member right remaining) (editor-set-focus! right)])
          (let ([return-to (loc.bookmark)])
            (for-each (lambda (doc)
                       (when (editor-doc-exists? doc)
                         (core.editor-switch-action! doc (Action/Replace))
                         (cmd.buffer-close!)))
              (unbox documents))
            (loc.restore (if (or (member left remaining) (member right remaining))
                          (hash-ref saved 'origin)
                          return-to)))))
      (set-box! documents (list))
      (chat.chat-restore (hash-ref saved 'chat)))))
